### ISSUE TITLE
Panics if used with inline mode

### ISSUE THREAD

**Issue by Eroc33** [bytesnake/telebot#1]
If a bot has iniline mode enabled and you start to use it by typing `@bot_name` it will panic with:
```
panicked at 'called `Result::unwrap()` on an `Err` value: Syntax(InvalidType(Map), 1, 18)'
```
Backtrace show it's at https://github.com/bytesnake/telebot/blob/master/src/functions.rs#L70 so I assume it's part of the derive'd code.

Edit: I see why now, there's no `InlineQuery` type, I'll see if I can fix this and open a PR.

**Comment by bytesnake** [comment]
Unfortunately I haven't test the library in inline mode yet. Thanks for the pull request though! I'll merge it but leave the issue open until the rest of the inline query API got implemented.
I'm not very content with the error message, perhaps there is a way to show that a part of Telegram isn't implemented yet.

**Comment by bytesnake** [comment]
The API for inline query is now supported, but the ergonomic can be improved. I've added a small example in examples/inline_query.rs.
