### ISSUE TITLE
answerInlineQuery optionals

### ISSUE THREAD

**Issue by gugahoa** [bytesnake/telebot#10]
The optionals should not be serialized if they're None, as it'll cause some unexpected behaviour, such as:
- Telegram sending updates for every entry because next_offset is set to "null" string (next_offset)
- Telegram setting button at the top of the answer with text "null" which goes to the PM (switch_pm_text)

How to reproduce:
- Run the inline_bot.rs example

Thanks for maintaining this library, I'm using it to develop a bot for a Rust community in Telegram (https://github.com/rust-br/crates-bot). As it grows in complexity I hope to contribute more with PR and other issues.

Cheers!

**Comment by bytesnake** [comment]
Hey there,
I haven't checked the InlineQuery example, and indeed there are some serde directives missing. The commit b90ebc6 should fix this. Please update your version number to 0.2.3. If you're encountering any further problems, please let me know. 
Thank you for using and testing the InlineQueries!
