### ISSUE TITLE
telebot::error::Error should implement std::error::Error

### ISSUE THREAD

**Issue by tecywiz121** [bytesnake/telebot#16]
Like it says in the Title, I think `telebot::error::Error` should probably implement `std::error::Error`. That'll let it work with the [error_chain](https://crates.io/crates/error-chain) crate.

**Comment by bytesnake** [comment]
Yes the library does not interop nicely with other errors. In future I want to use failure to handle the error enum, but it is not yet implemented. I'll try to update the implementation in the next days.
