### ISSUE TITLE
Crash on sending a game

### ISSUE THREAD

**Issue by l4l** [bytesnake/telebot#27]
```thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ErrorImpl { code: Message("invalid type: map, expected unit"), line: 1, column: 1732 }```

Quite simple: send a game - bot crash, [here's](https://gist.github.com/l4l/e15f8b9a02f56727ca367ac61b035307) the full backtrace of the example file

**Comment by bytesnake** [comment]
Yes games aren't yet supported by Telebot. You would need to add the missing functions and objects. It shouldn't crash the whole application though. Have you used one of the examples?

**Comment by bytesnake** [comment]
#28

**Comment by l4l** [comment]
Yeah, just copy-pasted; nightly compiler if it matters
