### ISSUE TITLE
Specify nightly version requirement

### ISSUE THREAD

**Issue by giovanniberti** [bytesnake/telebot#36]
Hi! I was trying this crate on stable (1.25) and it seems it requires nightly, as it depends on `telebot-derive` which uses a `#![feature]` macro. Specifically:

```
error[E0554]: #![feature] may not be used on the stable release channel
 --> /home/giova/.cargo/registry/src/github.com-1ecc6299db9ec823/telebot-derive-0.0.11/src/lib.rs:1:5
  |
1 |     #![feature(try_from)]
  |     ^^^^^^^^^^^^^^^^^^^^^

error[E0554]: #![feature] may not be used on the stable release channel
 --> /home/giova/.cargo/registry/src/github.com-1ecc6299db9ec823/telebot-derive-0.0.11/src/lib.rs:2:5
  |
2 |     #![feature(proc_macro, proc_macro_lib)]
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to 2 previous errors

error: Could not compile `telebot-derive`.
```

Am I doing something wrong or is nightly required to use this library?

**Comment by bytesnake** [comment]
Hey, I added a note to the README (4a19907818d999a4eb539dabd50bc51ea7c54d51) and created a new Issue for stable support (#38). I hope you find the approach there useful. Have a nice day.
