### ISSUE TITLE
Dead link in readme.md

### ISSUE THREAD

**Issue by senden9** [bytesnake/telebot#39]
The readme contains under [additional-example](https://github.com/bytesnake/telebot/tree/953a44b89c7542bd50688ccd639700f531a3055a#additional-example) a link to a `example.md` but the link is dead.

**Comment by bytesnake** [comment]
Hey, yep I totally forgot to write the file. My intention was to explain the error handling with futures, because it can be sometimes tricky. But don't despair! I just came up with a small tutorial in 2afee71a7382c586218591d1305a7327c5a1dacf :)
Have a nice day
