### ISSUE TITLE
Unused `enum ParseMode` 

### ISSUE THREAD

**Issue by Gowee** [bytesnake/telebot#49]
Hi.

There is https://github.com/bytesnake/telebot/blob/fc5bdaff33ebeb13170b67dfa3bd4a3c9e4386ae/src/functions.rs#L18

But it seems that it is not used anywhere

(

**Comment by bytesnake** [comment]
before 46c353633ddccf6720a5d251537b557aba0c7e8b you could use `parse_mode` as a function on any struct implementing it and feed it either with a String or the `ParseMode` struct (which implemented the Into<String> trait) But it is more sane to accept only `ParseMode`.
