### ISSUE TITLE
panic on forwarded channel posts

### ISSUE THREAD

**Issue by ratijas** [bytesnake/telebot#5]
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Syntax(MissingField("first_name"), 1, 226)' …
```

i guess it's the problem of code auto-generation in `telebot-derive` crate.

UPD: i think i found the root of the error.  it's line 61 of [`objects.rs`](https://github.com/bytesnake/telebot/blob/126729ecc7f597bc562de4f557fb226bb70156d0/src/objects.rs#L61):
`    pub forward_from_chat: Option<User>,`
it has to be `Option<Chat>` instead.

**Comment by bytesnake** [comment]
Thanks, this is indeed wrong. It would be awesome if Telegram could export their protocol to JSON or something, then we could autogenerate the fields.

**Comment by ratijas** [comment]
seems like tl schema is all json we could have :(

https://core.telegram.org/schema/json
