### ISSUE TITLE
Cannot send a file from filename

### ISSUE THREAD

**Issue by thomasfire** [bytesnake/telebot#60]
```
error[E0308]: mismatched types                                                                      
   --> src/bot.rs:252:9                                                                             
    |                                                                                               
252 |         bot.document(chat_id).file(filename.as_str()).send()                                    
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected opaque type, found a different opaque type
    |                                                                                               
    = note: expected type `impl bot::futures::Future` (opaque type)                                 
               found type `impl bot::futures::Future` (opaque type)
```
This error is shown on trying to send a file using construction, similar to bot.message(...).send()
So how to send a file?

**Comment by bytesnake** [comment]
Hey, can you give me an example? Normally this should work for any file

**Comment by thomasfire** [comment]
The example is https://github.com/thomasfire/teleprint/blob/de92e1e4e43abf60439eef6853b0a302bc44f870/src/bot.rs on the 252 line. If you remove the 253rd line and the semicolon on the 252nd, you'll get that error. Now I have my own implementation of it at newer versions.

**Comment by bytesnake** [comment]
I think you have to execute the second future in another `and_then` closure, like:
```rust
let handle = bot.new_cmd("/get_file").and_then(|(bot, msg)| {
    ...
    bot.document(admin).file(filename.as_str()).send().map(|_| bot)
}).and_then(|bot| {
    bot.message(admin, format!("/|\\ Your file\n | ")).send()
})
```

**Comment by thomasfire** [comment]
The code I gave you is compilable, the problem is when document.file.send is returned. I've made message sent as a crunch, not for real usability.

**Comment by bytesnake** [comment]
Yeah sure it will compile, but you don't dispatch the future to any task, so it probably won't get executed completely. You have either to join them together into a single future or spawn the second as well.
