### ISSUE TITLE
how upload photo from disk ?

### ISSUE THREAD

**Issue by robatipoor** [bytesnake/telebot#71]

**Comment by bytesnake** [comment]
You can find an example for a document here https://github.com/bytesnake/telebot/blob/master/examples/send_self.rs. The procedure is the same, you just replace the `document` with `photo`. 
```rust
let handle = bot.new_cmd("/send_self")
   .and_then(|(bot, msg)| bot.photo(msg.chat.id).file("photo.png").send())
   .for_each(|_| Ok(()));
```
If you have further questions, please reopen the issue :)

**Comment by robatipoor** [comment]
thank you
