### ISSUE TITLE
i need capture all text message from user no need cmd how i can ?

### ISSUE THREAD

**Issue by robatipoor** [bytesnake/telebot#72]
like this feature in golang telebot library 

b, _ := tb.NewBot(settings)

b.Handle(tb.OnText, func(m *tb.Message) {
	// all the text messages that weren't
	// captured by existing handlers
})

**Comment by bytesnake** [comment]
You can use the https://github.com/bytesnake/telebot/blob/master/examples/print_everything.rs example and filter the stream for messages with text. For example like this:
```rust
let stream = bot.get_stream(None)
   .filter_map(|(_,msg)| msg.text)
   .for_each(|text| {
      // process ...
      println!("Got text message {}", text); 
      Ok(())
   });
```

**Comment by robatipoor** [comment]
thanks
