### ISSUE TITLE
RcBot

### ISSUE THREAD

**Issue by senden9** [bytesnake/telebot#74]
There are references to a `RcBot` in the [documentation](https://docs.rs/telebot/0.3.0/telebot/bot/index.html?search=) but I can not find any `RcBot` implementation. 

What happened to `RcBot`? Obsolete? Renamed?

**Comment by bytesnake** [comment]
They were some remnants from the previous version. I removed them :)
Basically the `RcBot` was removed and instead a clonable `RequestHandle` introduced, which constructs and issues requests to the Telegram Server.
