### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by damirka** [bytesnake/telebot#75]
Couldn't get any working example: nor README, nor example.md do not work.

```text
rustc 1.41.0-nightly (5c5b8afd8 2019-11-16)
```

**Comment by bytesnake** [comment]
Well let's say that its on low-steam right now, what are your issues? Perhaps I can help to fix them. For examples you have to look into the `examples/` folder

**Comment by damirka** [comment]
Pardon. I will reply to use in next few days. Need to check everything again.
I remember there were some issues with one of the dependencies.

**Comment by damirka** [comment]
Looks like I didn't include "futures" into Cargo.toml. Problem solved.
