### ISSUE TITLE
Forwarding issue

### ISSUE THREAD

**Issue by MehmetKursat** [bytesnake/telebot#76]
I am trying to make the bot forward any message to another telegram acc, except from one specific chat. My code works if I simply forward every message coming from every chat id. However when I add conditions I can't satisfy the compiler, please tell me what I should return from that commented area.

```
   let stream = bot.clone().get_stream(None).and_then(|(bot, msg)| {
        //println!("{:?}", msg);
        let message_unwrapped = msg.message.unwrap();
        let chat_id = message_unwrapped.chat.id;
        let message_id = message_unwrapped.message_id;

        if chat_id == 000 {
          
            Either::A(
                // do nothing
                // what to write/return from here?
            )

        } else {
            Either::B(
                bot.forward(000, chat_id, message_id).send()
            )
        }

    }).for_each(move |(h, msg)| {
        Ok(())
    });

    tokio::run(stream.into_future().map_err(|_| ()));
```

**Comment by bytesnake** [comment]
Hey, I would prepend something like this:
```rust
 let stream = bot.clone().get_stream(None).
  .filter_map(|(bot,  msg)| {
        let message_unwrapped = msg.message.unwrap();

        if message_unwrapped.chat_id != 000 {
             Some((bot, message_unwrapped))
        } else {
             None
        }})
  .and_then(...)
```

**Comment by MehmetKursat** [comment]
Thank you so much, I am new to Rust and struggling so much, spent a day to figure this out and couldn't until now. Thanks again.

**Comment by bytesnake** [comment]
For sure, its hard to think in future combinators if not familiar with from other languages :) glad that I could save you some days figuring it out for yourself, if you have any further questions, just ask.
